In [1]:
import numpy as np

In [2]:
np_array = np.array([1,2,3])

In [3]:
np_array

array([1, 2, 3])

In [4]:
print(type(np_array))

<class 'numpy.ndarray'>


In [11]:
np_array = np.array([[1,2,3],[4,5,6]])

In [12]:
np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np_array.shape

(2, 3)

In [14]:
np_array.dtype

dtype('int32')

In [15]:
np_array.ndim

2

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [20]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

#### How is Numpy faster

In [27]:
c = range(1000)
%timeit cube_list = [i ** 3 for i in c]

225 µs ± 853 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [28]:
c_nparray = np.arange(1000)
%timeit c_nparray**3

3.04 µs ± 19.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [29]:
l1 = range(1000)
l2 = [i**2 for i in l1]

In [33]:
%timeit l3 = list(map((lambda x,y : x*y),l1,l2))

99.3 µs ± 506 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [34]:
l1 = np.arange(1000)
l2 = l1**2

In [35]:
%timeit l1*l2

1.27 µs ± 4.48 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### Numpy Functions

In [36]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.full((3,3),2,dtype=float)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [43]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [44]:
v = np.array([1,2,3])

In [45]:
v

array([1, 2, 3])

In [46]:
np.tile(v,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [47]:
np.tile(v,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [48]:
np.tile(v,(3,))

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [50]:
50*np.random.random(100) + 2

array([51.96480017, 10.31961012, 49.15180817,  3.55709507, 13.51330801,
       29.66645414, 17.55879618, 14.35494997, 42.24563621, 42.55177679,
       39.3812234 ,  6.27117429, 30.92758514,  8.61141891, 22.14815188,
       18.44303213, 40.18714705, 32.19681919, 14.30979425, 35.95532136,
       49.90177575, 13.52236666, 38.62158397, 45.13999031, 45.91953357,
       39.08238292, 20.79123236, 16.8919412 ,  6.1797356 ,  7.96014494,
       51.64314787,  5.86814471, 47.46634132, 15.50885111, 48.54295093,
       11.04079848,  6.45122902,  8.0071194 ,  7.79870579,  3.576023  ,
       23.5809823 , 26.09816243, 31.05986259,  7.43855706, 14.14733934,
       24.49342596,  3.6091233 , 42.73831856, 21.72624892, 32.90874499,
       51.83979552, 46.01577468, 15.90664807, 11.86022986, 50.80868335,
       10.93588911, 23.40659339, 34.07832968, 49.00553349, 29.56050633,
       28.7742736 , 43.84778029, 17.82793313,  9.1785329 ,  2.00948506,
        9.82349209, 39.30352557,  4.47673139, 46.80663232, 37.25

In [52]:
a = np.random.random((3,3))

In [53]:
a.itemsize

8

In [54]:
a = [[1,2,3],[4,5,6]]
b = [[7,8,9],[10,11,12]]

In [55]:
a = np.array(a)
b = np.array(b)

In [57]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [58]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [59]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [60]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [61]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619]])

In [62]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [63]:
np.sum(a)

21

In [64]:
np.median(a)

3.5

In [65]:
np.std(a)

1.707825127659933

In [67]:
a = np.arange(1,10).reshape(3,3)

In [68]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
np.linalg.det(a)

6.66133814775094e-16

In [70]:
np.linalg.inv(a)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [71]:
np.linalg.eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -4.22209278e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [73]:
b= a.T

In [74]:
np.dot(a,b)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])